services:
  # ----------------- Database -----------------
  postgres:
    image: postgres:15-alpine
    container_name: social-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------- Redis -----------------
  redis:
    image: redis:7-alpine
    container_name: social-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------- Backend (NestJS) -----------------
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    container_name: social-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
    - ./back/.env.production      
    volumes:
      - ./back/uploads:/app/uploads # for file uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ----------------- Frontend (Next.js) -----------------
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod   
    container_name: social-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001 # internal Docker network
      WATCHPACK_POLLING: true   
    #depends_on:
      #- backend
 
  