FROM node:24-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
EXPOSE 3001
CMD ["npm", "run", "start:dev"]


# docker compose -f docker-compose.dev.yml build --no-cache
# docker compose -f docker-compose.dev.yml up --force-recreate -d