# FROM node:24-alpine AS builder
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci --legacy-peer-deps
# COPY . .
# RUN npm run build

# FROM node:24-alpine
# WORKDIR /app
# COPY --from=builder /app/package*.json ./
# RUN npm ci --only=production --legacy-peer-deps
# # COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/.next ./.next
# COPY --from=builder /app/public ./public

# EXPOSE 3000
# CMD ["npm", "start"]

FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install  --legacy-peer-deps
COPY . .
RUN npm run build

FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev --legacy-peer-deps --only=production  
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["npm", "start"]